### PR TITLE
TINDER-71: Removing .toXML() and making the log computation dependent from level

### PR DESCRIPTION
**Pull request by cpetzka**
Implementation of: 
https://community.igniterealtime.org/thread/60969
and
https://issues.igniterealtime.org/browse/TINDER-71

### CODE REVIEW

**Comment by guusdk** [comment]
Thank you for your contribution! Are you sure that both `if (log.somelevelEnabled)` as well as not using `toXML()` is needed? I think only one of the solutions is enough: https://www.slf4j.org/faq.html#logging_performance

**Comment by cpetzka** [comment]
Hi,

i agree with you, the toXML is not needed if we use log.isDebugEnabled(). While implementing the pull request i recognized that the most log entries compute more than only the .toXML() like:

```
if (log.isDebugEnabled()){
  log.debug("(serving component '{}') Processing IQ (packetId {}): {}", new Object[] {getName(), iq.getID(), iq });
 }
```

The getName() method is abstract and can potential be expensive.

**Comment by GregDThomas** [comment]
Is this replaced by https://github.com/igniterealtime/tinder/pull/7 ?

**Comment by guusdk** [comment]
I'm closing this in favor of https://github.com/igniterealtime/tinder/pull/14 and https://github.com/igniterealtime/tinder/pull/7

If I missed anything that's in this PR, but not in the ones above, please let me know!

**Pull request closed without merging**
