### PR TITLE
Raise Java minimum requirements for version 8. Update plugin versions.

### PR DESCRIPTION
**Pull request by ma1uta**

### CODE REVIEW

**Comment by GregDThomas** [comment]
Your line endings have gone awry again. Copy https://github.com/igniterealtime/Openfire/blob/master/.editorconfig to the root of this project, it should stop it from happening.

**Comment by ma1uta** [comment]
I think the problem not with line ending (for example AbstractComponent has the `crlf` ending but the .editorconfig required only `lf`). In some classes I trimmed tail whitespaces.

**Comment by GregDThomas** [comment]
It's the pom.xml that's really the issue here; it's difficult to see what's changed (the other files are fine)

**Comment by GregDThomas** [comment]
I covered this off on another PR - 2.0.0-SNAPSHOT is now built on Java 8, tested using Java 8 + Java 11.

**Pull request closed without merging**
